Repository tl-its-umich-edu/my-learning-analytics, pull requests merged in 2019-12, with the labels that each got.

#775 Creating theme with default palette and consolidating color setting (#673 and #748)
  assets/src/components/RangeSlider.js
  assets/src/components/d3/createHistogram.js
  assets/src/components/d3/createHorizontalBar.js
  assets/src/components/d3/createProgressBar.js
  assets/src/components/d3/createResourceAccessChart.js
  assets/src/containers/App.js
  assets/src/containers/AssignmentPlanning.js
  assets/src/containers/GradeDistribution.js
  assets/src/containers/ResourcesAccessed.js
  assets/src/siteTheme.js
Labels: enhancement, react

#823 Update snackbar visualization time for issue #806 from branch issue-806-fix-snackbar-duration
  assets/src/components/UserSettingSnackbar.js
Labels: bug

#813 Made JS standard-compliant, standard added as dev-dependency
  CONTRIBUTING.md
  assets/src/__tests__/d3/__snapshots__/createHistogram.test.js.snap
  assets/src/__tests__/d3/createHistogram.test.js
  assets/src/__tests__/testData/assignmentViewTestData.js
  assets/src/__tests__/testData/d3TestData.js
  assets/src/__tests__/util/math.test.js
  assets/src/components/AlertBanner.js
  assets/src/components/Banner.js
  assets/src/components/GoogleAnalyticsTracking.js
  assets/src/components/HorizontalBar.js
  assets/src/components/ProgressBar.js
  assets/src/components/ResourceAccessChart.js
  assets/src/components/TableAssignment.js
  assets/src/components/UserSettingSnackbar.js
  assets/src/components/WarningBanner.js
  assets/src/components/d3/createHistogram.js
  assets/src/components/d3/createHorizontalBar.js
  assets/src/components/d3/createProgressBar.js
  assets/src/components/d3/createResourceAccessChart.js
  assets/src/containers/App.js
  assets/src/containers/AssignmentPlanning.js
  assets/src/containers/Course.js
  assets/src/containers/CourseList.js
  assets/src/containers/GradeDistribution.js
  assets/src/containers/ResourcesAccessed.js
  assets/src/containers/SideDrawer.js
  assets/src/index.js
  package.json
Labels: react
