Repository tl-its-umich-edu/my-learning-analytics, pull requests merged in 2020-07, with the labels that each got.

#978 #950 upgrade to python3.8
  Dockerfile
  requirements.txt
Labels: dependencies

#977 issue_964 add alert for course when course data is not available
  assets/src/containers/Course.js
  dashboard/views.py
Labels: react, 📈 enhancement

#988 API to support course config settings (#985)
  dashboard/rules.py
  dashboard/urls.py
  dashboard/views.py
  requirements.txt
Labels: Backend, ⚠️ priority

#983 Enable term management, improve cron methods (#963)
  dashboard/admin.py
  dashboard/cron.py
Labels: Backend, cron, 📈 enhancement
