Repository tl-its-umich-edu/my-learning-analytics, pull requests merged in 2020-08, with the labels that each got.

#993 Instructor page to configure MyLA courses
  assets/src/components/CourseListCard/CourseListCard.js
  assets/src/components/CourseListCard/CourseListCard.lazy.js
  assets/src/components/SelectCard.js
  assets/src/containers/App.js
  assets/src/containers/Course.js
  assets/src/containers/CourseList.js
  assets/src/containers/IndexPage.js
  assets/src/containers/SideDrawer.js
  assets/src/routes/routes.js
  assets/src/util/roles.js
  dashboard/common/db_util.py
  dashboard/common/utils.py
  dashboard/lti_new.py
  dashboard/views.py
  package.json
Labels: Frontend, UI, react, 📈 enhancement

#1014 Instructor preview
  assets/src/containers/AssignmentPlanning.js
  assets/src/containers/AssignmentPlanningV2.js
  assets/src/containers/Course.js
  assets/src/containers/GradeDistribution.js
  assets/src/containers/ResourcesAccessed.js
Labels: Frontend, react, 📈 enhancement

#1011 #826 - load MiVideo usage data from UDP
  config/env_sample.json
  dashboard/cron.py
Labels: backend, config change, ⚠️ priority

#1020 Supporting global view disable
  assets/src/routes/routes.js
  config/env_sample.json
  dashboard/views.py
Labels: backend, 📈 enhancement

#1010 #1009 fix for become_user and course links
  assets/src/containers/App.js
  assets/src/globals.js
  dashboard/common/db_util.py
  dashboard/common/utils.py
  dashboard/context_processors.py
  dashboard/lti_new.py
  dashboard/settings.py
Labels: backend

#1008 Add links to info about views on the course view page
  assets/src/components/AvatarModal.js
  assets/src/components/SelectCard.js
  assets/src/globals.js
  assets/src/routes/routes.js
  config/env_sample.json
  dashboard/common/utils.py
  dashboard/settings.py
Labels: Frontend, react, 📈 enhancement

#1033 Warn about old queries, but support them (#1025)
  dashboard/cron.py
Labels: bug, cron, ⚠️ priority
