Repository tl-its-umich-edu/my-learning-analytics, pull requests merged in 2020-02, with the labels that each got.

#862 Re-color resource links for consistency across browsers
  assets/src/components/d3/createResourceAccessChart.js
Labels: bug

#853 Modify palette colors and visualization text colors to improve contrast (#748, #805)
  assets/src/components/d3/createProgressBar.js
  assets/src/components/d3/createResourceAccessChart.js
  assets/src/defaultPalette.js
  config/env_sample.json
Labels: bug

#866 Fixes #865 - Cron except should be logged as exception
  dashboard/cron.py
  dashboard/settings.py
Labels: bug

#860 #857 insufficient grades count won't shown the view
  dashboard/views.py
Labels: bug

#868 Specify needed fields in course select query (#864)
  dashboard/cron.py
Labels: bug

#871 Replace not None check with pd.notna in update_datetime_field
  dashboard/cron.py
Labels: bug

#875 Add fallback empty object for mylaGlobals and update createHistogram test (#874)
  assets/src/__tests__/d3/__snapshots__/createHistogram.test.js.snap
  assets/src/globals.js
Labels: bug

#894 Adding trailing slash with course_enabled url
  dashboard/urls.py
Labels: bug

#898 Correct version ranges in requirements.txt (#897)
  requirements.txt
Labels: bug

#702 Redesign assignment
  assets/src/__tests__/components/AssignmentGradeBoxes.test.js
  assets/src/__tests__/components/Label.test.js
  assets/src/__tests__/components/Line.test.js
  assets/src/__tests__/components/ProgressBarV2.test.js
  assets/src/__tests__/components/__snapshots__/AssignmentGradeBoxes.test.js.snap
  assets/src/__tests__/components/__snapshots__/Label.test.js.snap
  assets/src/__tests__/components/__snapshots__/Line.test.js.snap
  assets/src/__tests__/components/__snapshots__/ProgressBarV2.test.js.snap
  assets/src/__tests__/components/d3/__snapshots__/createHistogram.test.js.snap
  assets/src/__tests__/components/d3/createHistogram.test.js
  assets/src/__tests__/util/assignment.test.js
  assets/src/__tests__/util/date.test.js
  assets/src/__tests__/util/math.test.js
  assets/src/components/AssignmentGoalInput.js
  assets/src/components/AssignmentTable.js
  assets/src/components/ConditionalWrapper.js
  assets/src/components/Label.js
  assets/src/components/Line.js
  assets/src/components/PopupMessage.js
  assets/src/components/ProgressBarV2.js
  assets/src/components/StyledTextField.js
  assets/src/components/d3/createHistogram.js
  assets/src/containers/AssignmentPlanning.js
  assets/src/containers/AssignmentPlanningV2.js
  assets/src/containers/Course.js
  assets/src/containers/GradeDistribution.js
  assets/src/hooks/useAssignmentData.js
  assets/src/hooks/useInitAssignmentState.js
  assets/src/hooks/useMathWarning.js
  assets/src/hooks/useSaveUserSetting.js
  assets/src/hooks/useSetUserSettingGQL.js
  assets/src/hooks/useSyncAssignmentAndGoalGrade.js
  assets/src/hooks/useUserAssignmentSetting.js
  assets/src/index.js
  assets/src/routes/routes.js
  assets/src/service/client.js
  assets/src/util/assignment.js
  assets/src/util/data.js
  assets/src/util/date.js
  assets/src/util/math.js
  dashboard/common/db_util.py
  dashboard/event_logs_types/event_logs_types.py
  dashboard/graphql/__init__.py
  dashboard/graphql/loaders.py
  dashboard/graphql/mutation.py
  dashboard/graphql/objects.py
  dashboard/graphql/query.py
  dashboard/graphql/schema.py
  dashboard/graphql/view.py
  dashboard/management/commands/course.py
  dashboard/migrations/0014_auto_20200116_1408.py
  dashboard/models.py
  dashboard/rules.py
  dashboard/settings.py
  dashboard/urls.py
  package.json
  requirements.txt
Labels: enhancement, in progress

#900 Provide unenrolled users with better feedback, add link color to palette (#785)
  assets/src/components/d3/createResourceAccessChart.js
  assets/src/containers/CourseList.js
  assets/src/defaultPalette.js
Labels: bug, react

#889 Fixes #886 #887 Course showing the percent of students accessing the file …
  assets/src/components/d3/createResourceAccessChart.js
  dashboard/views.py
Labels: UI : Resources Accessed, bug
