Repository tl-its-umich-edu/my-learning-analytics, pull requests merged in 2020-09, with the labels that each got.

#1064 Lock list of course IDs driving other cron methods after verification (#1062)
  dashboard/cron.py
Labels: backend, bug, cron

#1073 Only enable Django backend login methods if explicitly loaded or not …
  config/env_sample.json
  dashboard/settings.py
  dashboard/urls.py
Labels: backend, bug, config change

#1076 Remove Django Debug Toolbar …
  CONTRIBUTING.md
  dashboard/settings.py
  dashboard/urls.py
  requirements.txt
Labels: backend, dependencies

#1024 #1006 When adding a new course, need to update resource_access from the beginning of the term
  .vscode/launch.json
  dashboard/admin.py
  dashboard/common/db_util.py
  dashboard/common/utils.py
  dashboard/cron.py
  dashboard/migrations/0019_course_data_last_updated.py
  dashboard/models.py
Labels: backend, cron, django migration issue

#1074 add key generation management command (#1066)
  dashboard/management/commands/createkeys.py
  requirements.txt
Labels: backend, dependencies, 📈 enhancement

#1091 Add alt text for mouse on wheel loading image (#1082)
  assets/src/containers/Course.js
Labels: Frontend, accessibility, react

#1080 Updating settings to reference the expectation for the LOGOUT URL
  config/env_sample.json
Labels: documentation
