Repository tl-its-umich-edu/my-learning-analytics, pull requests merged in 2020-01, with the labels that each got.

#828 Improve docker-compose file system performance - Fixes #767
  docker-compose.yml
Labels: enhancement

#842 Update Python, Django, other dependencies, and streamline paths, views (#484, #485, #843)
  Dockerfile
  assets/src/containers/App.js
  config/env_sample.json
  dashboard/common/utils.py
  dashboard/context_processors.py
  dashboard/rules.py
  dashboard/settings.py
  dashboard/templates/base.html
  dashboard/urls.py
  dashboard/views.py
  requirements.txt
Labels: enhancement

#809 Home Buttons Have More Contrast When Keyboard Focused (#803)
  assets/src/containers/DashboardAppBar.js
Labels: bug

#845 Make primary color configurable and improve globals use by FE (#821)
  README.md
  assets/src/components/RangeSlider.js
  assets/src/components/d3/createHistogram.js
  assets/src/components/d3/createHorizontalBar.js
  assets/src/components/d3/createProgressBar.js
  assets/src/components/d3/createResourceAccessChart.js
  assets/src/containers/App.js
  assets/src/defaultPalette.js
  assets/src/globals.js
  assets/src/index.js
  assets/src/siteTheme.js
  config/env_sample.json
  dashboard/common/utils.py
  dashboard/settings.py
Labels: enhancement, react

#852 Fix typo in grade_distribution view (#851)
  dashboard/views.py
Labels: bug

#847 Move configuration of help URL from flatpages to settings.py (#846)
  config/env_sample.json
  dashboard/common/utils.py
  dashboard/settings.py
Labels: bug, config change

#848 Issue #301 added timestamp to BigQuery statements
  config/env_sample.json
  dashboard/common/utils.py
  dashboard/cron.py
Labels: config change
