Repository tl-its-umich-edu/my-learning-analytics, pull requests merged in 2020-05, with the labels that each got.

#931 Avoid warnings by using siteTheme.palette.negative.main, palette.link.main (#930)
  assets/src/containers/CourseList.js
  assets/src/containers/SideDrawer.js
  assets/src/defaultPalette.js
Labels: bug, react

#925 Issue 869: Added Icons to Checkboxes and Unified Fonts
  assets/src/components/IconLabel.js
  assets/src/components/d3/createResourceAccessChart.css
  assets/src/components/d3/createResourceAccessChart.js
  assets/src/containers/ResourcesAccessed.js
  assets/src/index.css
  dashboard/views.py
Labels: UI : Resources Accessed, accessibility, bug

#937 Bring back "View on Site" on "Change Course" page (#936)
  dashboard/models.py
Labels: bug, 📈 enhancement
