Repository tl-its-umich-edu/my-learning-analytics, pull requests merged in 2021-01, with the labels that each got.

#1182 Show PopUpMessage with assignment-specific progress bars when navigated to by keyboard (#800)
  assets/src/components/AssignmentTable.js
  assets/src/components/ProgressBarV2.js
  assets/src/hooks/usePopoverEl.js
Labels: Frontend, accessibility, 🐛 bug

#1185 #1184 fixes the docker build failure
  package.json
Labels: dependencies, 🐛 bug

#1172 Add modified admin delete confirmation templates for course (#1067)
  dashboard/templates/admin/dashboard/course/delete_confirmation.html
  dashboard/templates/admin/dashboard/course/delete_selected_confirmation.html
Labels: 📈 enhancement

#1189 Adding a separate Dockerfile for local openshift registry
  docker-compose-prod.yml
  docker-compose.yml
  dockerfiles/Dockerfile
  dockerfiles/Dockerfile.openshift
  dockerfiles/README.md
Labels: dependencies

#1202 issue_1201 return term end date directly if there is no term start date
  dashboard/models.py
Labels: backend, 🐛 bug

#1176 Adding adding survey button to top menu
  assets/src/components/SurveyModal.js
  assets/src/containers/DashboardAppBar.js
  assets/src/globals.js
  dashboard/common/utils.py
  dashboard/settings.py
  requirements.txt
Labels: Frontend, backend, dependencies, react, 📈 enhancement
