Repository tl-its-umich-edu/my-learning-analytics, pull requests merged in 2021-02, with the labels that each got.

#1232 Fixes #1217 - Make the survey button more noticable
  assets/src/components/SurveyModal.js
Labels: Frontend, 📈 enhancement

#1231 Refactor Line and Label components (#1168)
  assets/src/__tests__/components/Label.test.js
  assets/src/__tests__/components/Line.test.js
  assets/src/__tests__/components/ProgressBarV2.test.js
  assets/src/__tests__/components/__snapshots__/Label.test.js.snap
  assets/src/__tests__/components/__snapshots__/Line.test.js.snap
  assets/src/__tests__/components/__snapshots__/ProgressBarV2.test.js.snap
  assets/src/components/Label.js
  assets/src/components/Line.js
  assets/src/components/ProgressBarV2.js
  assets/src/containers/AssignmentPlanningV2.js
Labels: Frontend, UI : assignment (redesign), 📈 enhancement

#1234 Handle lack of Git environment variables better in util function and template (#1236)
  dashboard/common/utils.py
  dashboard/templates/base.html
Labels: backend, 📈 enhancement
