Repository tl-its-umich-edu/my-learning-analytics, pull requests merged in 2023-07, with the labels that each got.

#1518 Fix ability to edit courses via the admin and `canvas_id` readonly logic, improve validation (#1509)
  dashboard/admin.py
Labels: 🐛 bug, ⚙️ backend

#1517 I1515 node 18 upgrade
  dockerfiles/Dockerfile
  dockerfiles/Dockerfile.openshift
Labels: 📈 enhancement, dependencies

#1507 Removing old assignment planning view
  assets/images/assignments_planning_icon.png
  assets/src/components/AvatarModal.js
  assets/src/components/HorizontalBar.js
  assets/src/components/ProgressBar.js
  assets/src/components/TableAssignment.js
  assets/src/components/Tooltip.js
  assets/src/components/d3/createHorizontalBar.js
  assets/src/components/d3/createProgressBar.js
  assets/src/containers/AssignmentPlanning.js
  assets/src/containers/Course.js
  assets/src/hooks/useFetch.js
  assets/src/routes/routes.js
  assets/src/service/api.js
  config/env_sample.hjson
  dashboard/common/db_util.py
  dashboard/common/utils.py
  dashboard/event_logs_types/event_logs_types.py
  dashboard/management/commands/course.py
  dashboard/migrations/0025_remove_courseviewoption_show_assignment_planning_v1.py
  dashboard/models.py
  dashboard/rules.py
  dashboard/settings.py
  dashboard/urls.py
  dashboard/views.py
Labels: 📈 enhancement, backlog, django migration issue, Frontend, ⚙️ backend
