Repository tl-its-umich-edu/my-learning-analytics, pull requests merged in 2023-03, with the labels that each got.

#1488 Fixes #1466 - Limit display to a configurable number of resources
  assets/src/components/d3/createResourceAccessChart.js
  assets/src/containers/ResourcesAccessed.js
  dashboard/settings.py
  dashboard/views.py
Labels: 🐛 bug, Frontend, ⚙️ backend

#1496 Move to Google Analytics 4 (#1371)
  assets/src/components/GoogleAnalyticsTracking.js
  assets/src/containers/App.js
  assets/src/globals.js
  assets/src/index.js
  config/env_sample.hjson
  dashboard/templates/base.html
  package-lock.json
  package.json
Labels: 📈 enhancement, dependencies, Frontend

#1495 Change `class` prop to `className` in `SelectCard` (#1494)
  assets/src/components/SelectCard.js
Labels: 🐛 bug, Frontend

#1489 Fixes #1484 - MyLA importing incorrect timezone times
  config/cron.hjson
  config/cron_udp.hjson
  dashboard/cron.py
Labels: 🐛 bug, 📅 cron
